aliyun:
  sms:
    AccessKeyID: ${SMS_ACCESSKEYID}
    AccessKeySecret: ${SMS_ACCESSKEYSECRET}

spring:
  rabbitmq:
    host: rabbitmq
  datasource:
      druid:
        cuxsoa:
          read:
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:oracle:thin:@//cderpdb-scan.suntakpcb.com:1521/prod
            username: cux_soa
            password: cux_soa
            driver-class-name: oracle.jdbc.driver.OracleDriver
            initial-size: 2
            max-active: 5
            min-idle: 2
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: SELECT 1 from dual
            validation-query-timeout: 60000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
            max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
            filters: stat
          write:
            type: com.alibaba.druid.pool.DruidDataSource
            url: jdbc:oracle:thin:@//cderpdb-scan.suntakpcb.com:1521/prod
            username: cux_soa
            password: cux_soa
            driver-class-name: oracle.jdbc.driver.OracleDriver
            initial-size: 2
            max-active: 5
            min-idle: 2
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            validation-query: SELECT 1 from dual
            validation-query-timeout: 60000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
            max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
            filters: stat
