spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
          binder:
            headers: spanTraceId,spanId,spanParrentSpanId,spanProcessId
  zipkin:
    sender:
      type: kafka