version: '3.1'
services:
  configserver:
    image: suntak/cloud-config-server:$CLOUD_VERSION
    restart: always
    environment:
      - ENVIRONMENT=$ENVIRONMENT
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - GITLAB_USERNAME=$GITLAB_USERNAME
      - GITLAB_PASSWORD=$GITLAB_PASSWORD
      - KAFKA_SERVER=$KAFKA_SERVER
    ports:
     - "10001:10001"
networks:
  default:
    external:
      name: cloud

