version: '3.1'
services:
  recruitment:
    image: szmengran/cloud-suntak-recruitment:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10011:10011
networks:
  default:
    external:
      name: cloud