version: '3.1'
services:
  oauth:
    image: szmengran/cloud-security-oauth:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10002:10002
networks:
  default:
    external:
      name: cloud