version: '3.1'
services:
  discovery:
    image: suntak/cloud-discovery-eureka:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - "8761:8761"
  configserver:
    image: suntak/cloud-config-server:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - ENVIRONMENT=$ENVIRONMENT
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - GITLAB_USERNAME=$GITLAB_USERNAME
      - GITLAB_PASSWORD=$GITLAB_PASSWORD
    ports:
     - "10001:10001"
  gateway:
    image: suntak/cloud-gateway-zuul:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - "10000:10000"
  oauth:
    image: suntak/cloud-security-oauth:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10002:10002
  user:
    image: suntak/cloud-admin-user:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10003:10003
  sms:
    image: suntak/cloud-common-sms:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10004:10004
  ehr:
    image: suntak/cloud-suntak-ehr:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10005:10005
  suntak-sms:
    image: suntak/cloud-suntak-sms:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10006:10006
  questionnaire:
    image: suntak/cloud-suntak-questionnaire:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10007:10007
  activity:
    image: suntak/cloud-suntak-activity:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10008:10008
  test:
    image: suntak/cloud-suntak-test:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10009:10009
  recruitment:
    image: suntak/cloud-suntak-recruitment:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10011:10011
  wechat:
    image: suntak/cloud-suntak-wechat:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10014:10014
  microservices:
    image: suntak/microservices:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10101:10101
  haiwd:
    image: suntak/cloud-suntak-haiwd:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10016:10016
  warning:
    image: suntak/cloud-suntak-warning:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10022:10022
networks:
  default:
    external:
      name: cloud
