discovery:
  image: szmengran/cloud-discovery-eureka
  ports:
   - "8761:8761"
configserver:
  image: szmengran/cloud-config-server
  ports:
   - "8888:8888"
  links:
   - cloud-discovery-eureka
gateway:
  image: szmengran/cloud-gateway-zuul
  ports:
   - "10000:10000"
  links:
   - cloud-discovery-eureka
   - cloud-config-server
hystrix:
  image: szmengran/cloud-hystrix
  ports:
   - "7979:7979"
  links:
   - cloud-gateway-zuul
   - cloud-discovery-eureka