version: '3'
services:
  gateway:
    image: szmengran/cloud-gateway-zuul:$CLOUD_VERSION
    restart: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$CLOUD_ENVIRONMENT
    ports:
     - "10000:10000"