version: '3'
services:
  gateway:
    build: ../cloud-gateway/cloud-gateway-zuul
    image: szmengran/cloud-gateway-zuul:$CLOUD_VERSION
    restart: always
    ports:
     - "10000:10000"
    environment:
      ENVIRONMENT_ACTIVE: $ENVIRONMENT_ACTIVE
