version: '3'
services:
  oauth:
    image: szmengran/cloud-security-oauth
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:8888
      - ENVIRONMENT=dev
    ports:
     - 9999:9999