version: '3'
services:
  oauth:
    image: szmengran/cloud-security-oauth:$CLOUD_VERSION
    restart: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$CLOUD_ENVIRONMENT
    ports:
     - 10002:10002