version: '3.1'
services:
  gateway:
    image: suntak/cloud-gateway-zuul:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - "10000:10000"
  oauth:
    image: szmengran/cloud-security-oauth:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10002:10002
  user:
    image: szmengran/cloud-admin-user:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10003:10003
  sms:
    image: szmengran/cloud-common-sms:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10004:10004
  ehr:
    image: szmengran/cloud-suntak-ehr:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10005:10005
  suntak-sms:
    image: szmengran/cloud-suntak-sms:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10006:10006
  questionnaire:
    image: suntak/cloud-suntak-questionnaire:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10007:10007
  activity:
    image: szmengran/cloud-suntak-activity:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10008:10008
  test:
    image: szmengran/cloud-suntak-test:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10009:10009
  recruitment:
    image: szmengran/cloud-suntak-recruitment:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10011:10011
  wechat:
    image: suntak/cloud-suntak-wechat:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
    ports:
     - 10014:10014
  microservices:
    image: suntak/microservices:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=$EUREKA_SERVER_ADDRESS
      - CONFIG_SERVER_ADDRESS=$CONFIG_SERVER_ADDRESS
      - ENVIRONMENT=$ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10101:10101
networks:
  default:
    external:
      name: cloud