version: '3'
services:
  sms:
    image: szmengran/cloud-common-sms:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$CLOUD_ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10004:10004
networks:
  default:
    external:
      name: cloud