version: '3'
services:
  suntak-sms:
    image: szmengran/cloud-suntak-sms:$CLOUD_VERSION
    restart: always
    environment:
      - EUREKA_SERVER_ADDRESS=http://discovery:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:10001
      - ENVIRONMENT=$CLOUD_ENVIRONMENT
      - SMS_ACCESSKEYID=$SMS_ACCESSKEYID
      - SMS_ACCESSKEYSECRET=$SMS_ACCESSKEYSECRET
    ports:
     - 10006:10006